stages:       
  - deploy

Build-Dev:
  stage: deploy
  script:
    - echo "Compiling the code..."
    - sudo -s bash deploy-dev.sh
    - echo "Compile complete"
  tags: 
    - ics-dev-abmasoft
  only:
    - master
    
Build-Beta:
  stage: deploy
  script:
    - echo "Compiling the code..."
    - sudo -s bash deploy-beta.sh
    - echo "Compile complete"
  tags: 
    - eclipse-betaprod
  only:
    - beta-branch
